spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/english_app
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

app:
    jwtSecret:  TaZaSho?!
    jwtExpirationMs: 86400000

openapi: 3.0.3
info:
  title: Word service
  description: Word Learning Service
  version: "0.1"
paths:
  /word:
    post:
      summary: Add a new word.
      responses:
        '201':
          description: Created
